// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: an-gpon-pm-onu-traffic.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GponPmOnuTraffics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GponPmOnuTraffic []*GponPmOnuTraffics_GponPmOnuTraffic `protobuf:"bytes,1,rep,name=gpon_pm_onu_traffic,json=gpon-pm-onu-traffic,proto3" json:"gpon_pm_onu_traffic,omitempty"`
}

func (x *GponPmOnuTraffics) Reset() {
	*x = GponPmOnuTraffics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_an_gpon_pm_onu_traffic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GponPmOnuTraffics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GponPmOnuTraffics) ProtoMessage() {}

func (x *GponPmOnuTraffics) ProtoReflect() protoreflect.Message {
	mi := &file_an_gpon_pm_onu_traffic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GponPmOnuTraffics.ProtoReflect.Descriptor instead.
func (*GponPmOnuTraffics) Descriptor() ([]byte, []int) {
	return file_an_gpon_pm_onu_traffic_proto_rawDescGZIP(), []int{0}
}

func (x *GponPmOnuTraffics) GetGponPmOnuTraffic() []*GponPmOnuTraffics_GponPmOnuTraffic {
	if x != nil {
		return x.GponPmOnuTraffic
	}
	return nil
}

type GponPmOnuTraffics_GponPmOnuTraffic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//ONU���ƣ���ʽ��v_ani.f.s.p.ONUid
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//ONU����ƽ�����ʣ���λkbps
	TxRate uint32 `protobuf:"varint,2,opt,name=tx_rate,json=tx-rate,proto3" json:"tx_rate,omitempty"`
	//ONU����ƽ�����ʣ���λkbps
	RxRate uint32 `protobuf:"varint,3,opt,name=rx_rate,json=rx-rate,proto3" json:"rx_rate,omitempty"`
	//ONU�����뼶��ֵ���ʣ���λkbps
	TxPeakRate uint32 `protobuf:"varint,4,opt,name=tx_peak_rate,json=tx-peak-rate,proto3" json:"tx_peak_rate,omitempty"`
	//ONU�����뼶��ֵ���ʣ���λkbps
	RxPeakRate uint32 `protobuf:"varint,5,opt,name=rx_peak_rate,json=rx-peak-rate,proto3" json:"rx_peak_rate,omitempty"`
}

func (x *GponPmOnuTraffics_GponPmOnuTraffic) Reset() {
	*x = GponPmOnuTraffics_GponPmOnuTraffic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_an_gpon_pm_onu_traffic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GponPmOnuTraffics_GponPmOnuTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GponPmOnuTraffics_GponPmOnuTraffic) ProtoMessage() {}

func (x *GponPmOnuTraffics_GponPmOnuTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_an_gpon_pm_onu_traffic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GponPmOnuTraffics_GponPmOnuTraffic.ProtoReflect.Descriptor instead.
func (*GponPmOnuTraffics_GponPmOnuTraffic) Descriptor() ([]byte, []int) {
	return file_an_gpon_pm_onu_traffic_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GponPmOnuTraffics_GponPmOnuTraffic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GponPmOnuTraffics_GponPmOnuTraffic) GetTxRate() uint32 {
	if x != nil {
		return x.TxRate
	}
	return 0
}

func (x *GponPmOnuTraffics_GponPmOnuTraffic) GetRxRate() uint32 {
	if x != nil {
		return x.RxRate
	}
	return 0
}

func (x *GponPmOnuTraffics_GponPmOnuTraffic) GetTxPeakRate() uint32 {
	if x != nil {
		return x.TxPeakRate
	}
	return 0
}

func (x *GponPmOnuTraffics_GponPmOnuTraffic) GetRxPeakRate() uint32 {
	if x != nil {
		return x.RxPeakRate
	}
	return 0
}

var File_an_gpon_pm_onu_traffic_proto protoreflect.FileDescriptor

var file_an_gpon_pm_onu_traffic_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x6e, 0x2d, 0x67, 0x70, 0x6f, 0x6e, 0x2d, 0x70, 0x6d, 0x2d, 0x6f, 0x6e, 0x75,
	0x2d, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x61, 0x6e, 0x5f, 0x67, 0x70, 0x6f, 0x6e, 0x5f, 0x70, 0x6d, 0x5f, 0x6f, 0x6e, 0x75, 0x5f, 0x74,
	0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x22, 0xa6, 0x02, 0x0a, 0x11, 0x47, 0x70, 0x6f, 0x6e, 0x50,
	0x6d, 0x4f, 0x6e, 0x75, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x73, 0x12, 0x6c, 0x0a, 0x13,
	0x67, 0x70, 0x6f, 0x6e, 0x5f, 0x70, 0x6d, 0x5f, 0x6f, 0x6e, 0x75, 0x5f, 0x74, 0x72, 0x61, 0x66,
	0x66, 0x69, 0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x61, 0x6e, 0x5f, 0x67,
	0x70, 0x6f, 0x6e, 0x5f, 0x70, 0x6d, 0x5f, 0x6f, 0x6e, 0x75, 0x5f, 0x74, 0x72, 0x61, 0x66, 0x66,
	0x69, 0x63, 0x2e, 0x47, 0x70, 0x6f, 0x6e, 0x50, 0x6d, 0x4f, 0x6e, 0x75, 0x54, 0x72, 0x61, 0x66,
	0x66, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x70, 0x6f, 0x6e, 0x50, 0x6d, 0x4f, 0x6e, 0x75, 0x54, 0x72,
	0x61, 0x66, 0x66, 0x69, 0x63, 0x52, 0x13, 0x67, 0x70, 0x6f, 0x6e, 0x2d, 0x70, 0x6d, 0x2d, 0x6f,
	0x6e, 0x75, 0x2d, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x1a, 0xa2, 0x01, 0x0a, 0x10, 0x47,
	0x70, 0x6f, 0x6e, 0x50, 0x6d, 0x4f, 0x6e, 0x75, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x78, 0x2d, 0x72, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x78, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x72, 0x78, 0x2d, 0x72, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x78, 0x5f, 0x70, 0x65,
	0x61, 0x6b, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x74,
	0x78, 0x2d, 0x70, 0x65, 0x61, 0x6b, 0x2d, 0x72, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72,
	0x78, 0x5f, 0x70, 0x65, 0x61, 0x6b, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x72, 0x78, 0x2d, 0x70, 0x65, 0x61, 0x6b, 0x2d, 0x72, 0x61, 0x74, 0x65, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_an_gpon_pm_onu_traffic_proto_rawDescOnce sync.Once
	file_an_gpon_pm_onu_traffic_proto_rawDescData = file_an_gpon_pm_onu_traffic_proto_rawDesc
)

func file_an_gpon_pm_onu_traffic_proto_rawDescGZIP() []byte {
	file_an_gpon_pm_onu_traffic_proto_rawDescOnce.Do(func() {
		file_an_gpon_pm_onu_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(file_an_gpon_pm_onu_traffic_proto_rawDescData)
	})
	return file_an_gpon_pm_onu_traffic_proto_rawDescData
}

var file_an_gpon_pm_onu_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_an_gpon_pm_onu_traffic_proto_goTypes = []interface{}{
	(*GponPmOnuTraffics)(nil),                  // 0: an_gpon_pm_onu_traffic.GponPmOnuTraffics
	(*GponPmOnuTraffics_GponPmOnuTraffic)(nil), // 1: an_gpon_pm_onu_traffic.GponPmOnuTraffics.GponPmOnuTraffic
}
var file_an_gpon_pm_onu_traffic_proto_depIdxs = []int32{
	1, // 0: an_gpon_pm_onu_traffic.GponPmOnuTraffics.gpon_pm_onu_traffic:type_name -> an_gpon_pm_onu_traffic.GponPmOnuTraffics.GponPmOnuTraffic
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_an_gpon_pm_onu_traffic_proto_init() }
func file_an_gpon_pm_onu_traffic_proto_init() {
	if File_an_gpon_pm_onu_traffic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_an_gpon_pm_onu_traffic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GponPmOnuTraffics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_an_gpon_pm_onu_traffic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GponPmOnuTraffics_GponPmOnuTraffic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_an_gpon_pm_onu_traffic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_an_gpon_pm_onu_traffic_proto_goTypes,
		DependencyIndexes: file_an_gpon_pm_onu_traffic_proto_depIdxs,
		MessageInfos:      file_an_gpon_pm_onu_traffic_proto_msgTypes,
	}.Build()
	File_an_gpon_pm_onu_traffic_proto = out.File
	file_an_gpon_pm_onu_traffic_proto_rawDesc = nil
	file_an_gpon_pm_onu_traffic_proto_goTypes = nil
	file_an_gpon_pm_onu_traffic_proto_depIdxs = nil
}
