// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: an-gpon-pm-onu-local-info.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GponPmOnuLocalInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GponPmOnuLocalInfo []*GponPmOnuLocalInfos_GponPmOnuLocalInfo `protobuf:"bytes,1,rep,name=gpon_pm_onu_local_info,json=gpon-pm-onu-local-info,proto3" json:"gpon_pm_onu_local_info,omitempty"`
}

func (x *GponPmOnuLocalInfos) Reset() {
	*x = GponPmOnuLocalInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_an_gpon_pm_onu_local_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GponPmOnuLocalInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GponPmOnuLocalInfos) ProtoMessage() {}

func (x *GponPmOnuLocalInfos) ProtoReflect() protoreflect.Message {
	mi := &file_an_gpon_pm_onu_local_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GponPmOnuLocalInfos.ProtoReflect.Descriptor instead.
func (*GponPmOnuLocalInfos) Descriptor() ([]byte, []int) {
	return file_an_gpon_pm_onu_local_info_proto_rawDescGZIP(), []int{0}
}

func (x *GponPmOnuLocalInfos) GetGponPmOnuLocalInfo() []*GponPmOnuLocalInfos_GponPmOnuLocalInfo {
	if x != nil {
		return x.GponPmOnuLocalInfo
	}
	return nil
}

type GponPmOnuLocalInfos_GponPmOnuLocalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//ONU���ƣ���ʽ��v_ani.f.s.p.onuid
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//OLT��ģ����յ�ONU�Ĺ⹦�ʣ���λ��0.01dBm
	OltRxPower int32 `protobuf:"varint,2,opt,name=olt_rx_power,json=olt-rx-power,proto3" json:"olt_rx_power,omitempty"`
	//����ʱ������λ��
	OnlineDuration uint32 `protobuf:"varint,3,opt,name=online_duration,json=online-duration,proto3" json:"online_duration,omitempty"`
	//���һ������ʱ�䣬��1970�꿪ʼ������
	LastDownTime uint32 `protobuf:"varint,4,opt,name=last_down_time,json=last-down-time,proto3" json:"last_down_time,omitempty"`
	//���һ������ԭ��
	//The value (0) indicates that the reason is unknown��
	//The value (1) indicates that the reason is LOS(Loss of signal)��
	//The value (2) indicates that the reason is LOSi(Loss of signal for ONUi) or LOBi (Loss of burst for ONUi)��
	//The value (3) indicates that the reason is LOFI(Loss of frame of ONUi)��
	//The value (4) indicates that the reason is SFI(Signal fail of ONUi)��
	//The value (5) indicates that the reason is LOAI(Loss of acknowledge with ONUi)��
	//The value (6) indicates that the reason is LOAMI(Loss of PLOAM for ONUi)��
	//The value (7) indicates that the reason is deactive ONT fails��
	//The value (8) indicates that the reason is deactive ONT success��
	//The value (9) indicates that the reason is reset ONT��
	//The value (10) indicates that the reason is re-register ONT��
	//The value (11) indicates that the reason is pop up fail��
	//The value (13) indicates that the reason is dying-gasp��
	//The value (15) indicates that the reason is LOKI(Loss of key synch with ONUi)��
	//The value (18) indicates that the reason is deactived ONT due to the ring��
	//The value (30) indicates that the reason is shut down ONT optical module��
	//The value (255) indicates that the query fails.
	LastDownCause uint32 `protobuf:"varint,5,opt,name=last_down_cause,json=last-down-cause,proto3" json:"last_down_cause,omitempty"`
	//ONU״̬��1-online��2-offline��255-invalid
	OnuStatus uint32 `protobuf:"varint,6,opt,name=onu_status,json=onu-status,proto3" json:"onu_status,omitempty"`
}

func (x *GponPmOnuLocalInfos_GponPmOnuLocalInfo) Reset() {
	*x = GponPmOnuLocalInfos_GponPmOnuLocalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_an_gpon_pm_onu_local_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GponPmOnuLocalInfos_GponPmOnuLocalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GponPmOnuLocalInfos_GponPmOnuLocalInfo) ProtoMessage() {}

func (x *GponPmOnuLocalInfos_GponPmOnuLocalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_an_gpon_pm_onu_local_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GponPmOnuLocalInfos_GponPmOnuLocalInfo.ProtoReflect.Descriptor instead.
func (*GponPmOnuLocalInfos_GponPmOnuLocalInfo) Descriptor() ([]byte, []int) {
	return file_an_gpon_pm_onu_local_info_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GponPmOnuLocalInfos_GponPmOnuLocalInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GponPmOnuLocalInfos_GponPmOnuLocalInfo) GetOltRxPower() int32 {
	if x != nil {
		return x.OltRxPower
	}
	return 0
}

func (x *GponPmOnuLocalInfos_GponPmOnuLocalInfo) GetOnlineDuration() uint32 {
	if x != nil {
		return x.OnlineDuration
	}
	return 0
}

func (x *GponPmOnuLocalInfos_GponPmOnuLocalInfo) GetLastDownTime() uint32 {
	if x != nil {
		return x.LastDownTime
	}
	return 0
}

func (x *GponPmOnuLocalInfos_GponPmOnuLocalInfo) GetLastDownCause() uint32 {
	if x != nil {
		return x.LastDownCause
	}
	return 0
}

func (x *GponPmOnuLocalInfos_GponPmOnuLocalInfo) GetOnuStatus() uint32 {
	if x != nil {
		return x.OnuStatus
	}
	return 0
}

var File_an_gpon_pm_onu_local_info_proto protoreflect.FileDescriptor

var file_an_gpon_pm_onu_local_info_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x6e, 0x2d, 0x67, 0x70, 0x6f, 0x6e, 0x2d, 0x70, 0x6d, 0x2d, 0x6f, 0x6e, 0x75,
	0x2d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2d, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x19, 0x61, 0x6e, 0x5f, 0x67, 0x70, 0x6f, 0x6e, 0x5f, 0x70, 0x6d, 0x5f, 0x6f, 0x6e,
	0x75, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xfb, 0x02, 0x0a,
	0x13, 0x47, 0x70, 0x6f, 0x6e, 0x50, 0x6d, 0x4f, 0x6e, 0x75, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x12, 0x79, 0x0a, 0x16, 0x67, 0x70, 0x6f, 0x6e, 0x5f, 0x70, 0x6d, 0x5f,
	0x6f, 0x6e, 0x75, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x61, 0x6e, 0x5f, 0x67, 0x70, 0x6f, 0x6e, 0x5f, 0x70,
	0x6d, 0x5f, 0x6f, 0x6e, 0x75, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x47, 0x70, 0x6f, 0x6e, 0x50, 0x6d, 0x4f, 0x6e, 0x75, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x2e, 0x47, 0x70, 0x6f, 0x6e, 0x50, 0x6d, 0x4f, 0x6e, 0x75, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x16, 0x67, 0x70, 0x6f, 0x6e, 0x2d, 0x70, 0x6d,
	0x2d, 0x6f, 0x6e, 0x75, 0x2d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2d, 0x69, 0x6e, 0x66, 0x6f, 0x1a,
	0xe8, 0x01, 0x0a, 0x12, 0x47, 0x70, 0x6f, 0x6e, 0x50, 0x6d, 0x4f, 0x6e, 0x75, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x6c,
	0x74, 0x5f, 0x72, 0x78, 0x5f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x6f, 0x6c, 0x74, 0x2d, 0x72, 0x78, 0x2d, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x28,
	0x0a, 0x0f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2d,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x2d, 0x64, 0x6f, 0x77, 0x6e, 0x2d, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x28, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x63, 0x61,
	0x75, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x2d,
	0x64, 0x6f, 0x77, 0x6e, 0x2d, 0x63, 0x61, 0x75, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x6e,
	0x75, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x6f, 0x6e, 0x75, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_an_gpon_pm_onu_local_info_proto_rawDescOnce sync.Once
	file_an_gpon_pm_onu_local_info_proto_rawDescData = file_an_gpon_pm_onu_local_info_proto_rawDesc
)

func file_an_gpon_pm_onu_local_info_proto_rawDescGZIP() []byte {
	file_an_gpon_pm_onu_local_info_proto_rawDescOnce.Do(func() {
		file_an_gpon_pm_onu_local_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_an_gpon_pm_onu_local_info_proto_rawDescData)
	})
	return file_an_gpon_pm_onu_local_info_proto_rawDescData
}

var file_an_gpon_pm_onu_local_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_an_gpon_pm_onu_local_info_proto_goTypes = []interface{}{
	(*GponPmOnuLocalInfos)(nil),                    // 0: an_gpon_pm_onu_local_info.GponPmOnuLocalInfos
	(*GponPmOnuLocalInfos_GponPmOnuLocalInfo)(nil), // 1: an_gpon_pm_onu_local_info.GponPmOnuLocalInfos.GponPmOnuLocalInfo
}
var file_an_gpon_pm_onu_local_info_proto_depIdxs = []int32{
	1, // 0: an_gpon_pm_onu_local_info.GponPmOnuLocalInfos.gpon_pm_onu_local_info:type_name -> an_gpon_pm_onu_local_info.GponPmOnuLocalInfos.GponPmOnuLocalInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_an_gpon_pm_onu_local_info_proto_init() }
func file_an_gpon_pm_onu_local_info_proto_init() {
	if File_an_gpon_pm_onu_local_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_an_gpon_pm_onu_local_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GponPmOnuLocalInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_an_gpon_pm_onu_local_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GponPmOnuLocalInfos_GponPmOnuLocalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_an_gpon_pm_onu_local_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_an_gpon_pm_onu_local_info_proto_goTypes,
		DependencyIndexes: file_an_gpon_pm_onu_local_info_proto_depIdxs,
		MessageInfos:      file_an_gpon_pm_onu_local_info_proto_msgTypes,
	}.Build()
	File_an_gpon_pm_onu_local_info_proto = out.File
	file_an_gpon_pm_onu_local_info_proto_rawDesc = nil
	file_an_gpon_pm_onu_local_info_proto_goTypes = nil
	file_an_gpon_pm_onu_local_info_proto_depIdxs = nil
}
